#!/bin/bash
# This script installs or copies all the right files to the right location.
#

link()
{
	if [ -h "${2}" ]; then
		LNKDST=$(readlink -f "${2}")
		if [ "${1}" -ef "${LNKDST}" ]; then
			printf "Skip linking [${YELLOW}${1}${NC}] -\> [${YELLOW}${2}${NC}]\n"
			return
		fi
	fi

	if [ -f "${2}" ]; then
		BAKFNAME=${2}.bak.${RANDOM}
		printf "Backup file [${YELLOW}${2}${NC}] -\> [${YELLOW}${BAKFNAME}${NC}]\n"
		mv "${2}" "${BAKFNAME}"
	fi

	printf "Linking [${YELLOW}${1}${NC}] -\> [${YELLOW}${2}${NC}]\n"
	ln -s "${1}" "${2}"
}

mkfolder()
{
	if [ ! -d "${1}" ]; then
		mkdir "${1}"
	fi
}

CWD=$(dirname "$(realpath -s $0)")
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
clear
read -p "Press [Enter] key to install files into HOME directory at . . ."

printf "Building .vimrc . . .\n"
cat vimrc.vim > "${HOME}/.vimrc"
cat keymap.vim >> "${HOME}/.vimrc"
cat filetypes.vim >> "${HOME}/.vimrc"
cat functions.vim >> "${HOME}/.vimrc"
cat pop.vim >> "${HOME}/.vimrc"
cat git.vim >> "${HOME}/.vimrc"

printf "Building .gvimrc . . .\n"
cat gvimrc.vim > "${HOME}/.gvimrc"

# THEMES
mkdir -p "${HOME}/.vim/colors"
link "${CWD}/Dark+.vim" "${HOME}/.vim/colors/Dark+.vim"

# SYNTAX
mkdir -p "${HOME}/.vim/syntax"
link "${CWD}/cs.vim" "${HOME}/.vim/syntax/cs.vim"
link "${CWD}/gitmisc.vim" "${HOME}/.vim/syntax/gitmisc.vim"
