#!/bin/bash
# This script installs or copies all the right files to the right location.
#

link()
{
    if [ -h "${2}" ]; then
        LNKDST=$(readlink -f "${2}")
        if [ "${1}" -ef "${LNKDST}" ]; then
            printf "Skip linking [${YELLOW}${1}${NC}] -\> [${YELLOW}${2}${NC}]\n"
            return
        fi
    fi

    if [ -f "${2}" ]; then
        BAKFNAME=${2}.bak.${RANDOM}
        printf "Backup file [${YELLOW}${2}${NC}] -\> [${YELLOW}${BAKFNAME}${NC}]\n"
        mv "${2}" "${BAKFNAME}"
    fi

    printf "Linking [${YELLOW}${1}${NC}] -\> [${YELLOW}${2}${NC}]\n"
    ln -s "${1}" "${2}"
}

mkfolder()
{
    if [ ! -d "${1}" ]; then
        mkdir "${1}"
    fi
}

CWD=$(dirname "$(realpath -s $0)")
YELLOW='\033[1;33m'
NC='\033[0m' # No Color
clear
read -p "Press [Enter] key to install files into HOME directory at . . ."

printf "Building .vimrc . . .\n"
cat "${CWD}/vimrc.vim" > "${HOME}/.vimrc"
if [ "${OSTYPE}" == "linux" ]; then
    cat "${CWD}/vimrc-linux.vim" >> "${HOME}/.vimrc"
else
    cat "${CWD}/vimrc-win32.vim" >> "${HOME}/.vimrc"
fi

cat "${CWD}/nerdtree.vim" >> "${HOME}/.vimrc"
cat "${CWD}/keymap.vim" >> "${HOME}/.vimrc"

cat "${CWD}/trivial.vim" >> "${HOME}/.vimrc"
if [ "${OSTYPE}" == "linux" ]; then
    cat "${CWD}/trivial-linux.vim" >> "${HOME}/.vimrc"
else
    cat "${CWD}/trivial-win32.vim" >> "${HOME}/.vimrc"
fi

cat "${CWD}/functions.vim" >> "${HOME}/.vimrc"
cat "${CWD}/debug.vim" >> "${HOME}/.vimrc"
cat "${CWD}/git.vim" >> "${HOME}/.vimrc"
cat "${CWD}/gitshow.vim" >> "${HOME}/.vimrc"
cat "${CWD}/gitcommit.vim" >> "${HOME}/.vimrc"
cat "${CWD}/gitinspect.vim" >> "${HOME}/.vimrc"
cat "${CWD}/gitlog.vim" >> "${HOME}/.vimrc"
cat "${CWD}/gitbranch.vim" >> "${HOME}/.vimrc"
cat "${CWD}/gitstatus.vim" >> "${HOME}/.vimrc"
cat "${CWD}/csharp.vim" >> "${HOME}/.vimrc"
cat "${CWD}/goto.vim" >> "${HOME}/.vimrc"
cat "${CWD}/omnisharp.vim" >> "${HOME}/.vimrc"
cat "${CWD}/menu.vim" >> "${HOME}/.vimrc"

# DELETE COMMENTS
sed -i '/^\s*#\s.*/d' "${HOME}/.vimrc"
sed -i '/^#.*/d' "${HOME}/.vimrc"
sed -i '/^\".*/d' "${HOME}/.vimrc"

# DELETE BLANK LINES
sed -i /^$/d "${HOME}/.vimrc"

# REMOVE LEADING|TRAILING WHITESPACE
sed -i 's/^[ \t]*//;s/[ \t]*$//' "${HOME}/.vimrc"

printf "Building .gvimrc . . .\n"
cat "${CWD}/gvimrc.vim" > "${HOME}/.gvimrc"
if [ "${OSTYPE}" == "linux" ]; then
    cat "${CWD}/gvimrc-linux.vim" >> "${HOME}/.gvimrc"
else
    cat "${CWD}/gvimrc-win32.vim" >> "${HOME}/.gvimrc"
fi


if [ "${OSTYPE}" == "linux" ]; then
    VIMDIR=.vim
else
    VIMDIR=vimfiles
fi

# POPUP
cat "${CWD}/menu.txt" > "${HOME}/${VIMDIR}/menu.txt"
cat "${CWD}/keys.html" > "${HOME}/${VIMDIR}/keys.html"


# THEMES
mkdir -p "${HOME}/${VIMDIR}/colors"
cat "${CWD}/Dark+.vim" > "${HOME}/${VIMDIR}/colors/Dark+.vim"

# SYNTAX
mkdir -p "${HOME}/${VIMDIR}/syntax"
cat "${CWD}/cs.vim" > "${HOME}/${VIMDIR}/syntax/cs.vim"
